"""Schemas for the brand_dna module: canonical document contract and API resources.

The canonical document contract (`BrandDnaDocument`) is strict (extra="forbid"):
every string is trimmed before validation/persistence, empty-after-trim strings
are invalid, types/cardinalities/limits match design.md exactly, and unknown
sections, fields or keys are rejected with 422 and their field paths. It now
lives in `app.ai.contracts` (change 013): that module is the AI Platform's
contract boundary, and `run_capability` validates generation output against
this exact same contract manual authoring persists. This module imports it
from there rather than redefining it (single definition, one direction of
dependency — same pattern `app.creative.schemas` uses).
"""

import uuid
from datetime import datetime
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, StringConstraints

from app.ai.contracts import BrandDnaDocument, Example300, Label60, Narrative500
from app.brand_dna.models import BrandDnaStatus, KnowledgeStatus

# Re-exported for backward compatibility: pre-013 code imported this constant
# from this module.
MAX_DOCUMENT_BYTES = 32 * 1024

# Brief input fields (change 013) are a distinct, smaller shape than the
# document contract above: short single-line values, not narrative sections.
BriefField = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=120)]


class _Strict(BaseModel):
    model_config = ConfigDict(extra="forbid")


class BrandBasicsIn(_Strict):
    brand_name: BriefField
    offering: BriefField
    description: Narrative500 | None = None


class AudienceIn(_Strict):
    primary_audience: BriefField
    market: BriefField
    description: Narrative500
    tags: list[Label60] = Field(default_factory=list, max_length=10)


class PersonalityToneIn(_Strict):
    traits: list[Label60] = Field(min_length=1, max_length=10)


class BrandRulesIn(_Strict):
    always: list[Example300] = Field(min_length=1, max_length=20)
    never: list[Example300] = Field(min_length=1, max_length=20)


class BrandBriefIn(_Strict):
    """Onboarding brief that seeds AI generation of the Brand DNA draft.

    Matches the 'Create Brand DNA' screen (starter-design/Content Suite.dc.html):
    Brand Basics, Audience, Personality & Tone, Brand Rules.
    """

    basics: BrandBasicsIn
    audience: AudienceIn
    personality: PersonalityToneIn
    rules: BrandRulesIn


def derive_section_counts(document: BrandDnaDocument) -> dict[str, int]:
    """Deterministic per-section summary: one entry per atomic unit.

    A unit is a list item or a narrative/scalar field, so every section yields
    a stable count derived from the document itself (no denormalized counters):
    identity = 3 narratives + traits; voice = guide + its 5 lists;
    communication = pillars + rules; visual_rules = its 4 narratives;
    restrictions = rules.
    """
    return {
        "identity": 3 + len(document.identity.personality_traits),
        "voice": 1
        + len(document.voice.tone_characteristics)
        + len(document.voice.preferred_vocabulary)
        + len(document.voice.avoid_vocabulary)
        + len(document.voice.do_examples)
        + len(document.voice.dont_examples),
        "communication": len(document.communication.message_pillars)
        + len(document.communication.rules),
        "visual_rules": 4,
        "restrictions": len(document.restrictions.rules),
    }


class BrandDnaVersionOut(BaseModel):
    id: uuid.UUID
    brand_id: uuid.UUID
    version: int
    status: BrandDnaStatus
    document: BrandDnaDocument
    created_by: uuid.UUID
    created_at: datetime
    published_at: datetime | None
    knowledge_status: KnowledgeStatus
    section_counts: dict[str, int]
    # The brief that originated a generation (change 013), distinct from the
    # document itself; null when the version was never generated by AI or a
    # manual edit replaced the document without touching this field.
    brief: dict[str, Any] | None = None


class BrandDnaVersionSummary(BaseModel):
    """Version resource without the full document (history list entries)."""

    id: uuid.UUID
    brand_id: uuid.UUID
    version: int
    status: BrandDnaStatus
    created_by: uuid.UUID
    created_at: datetime
    published_at: datetime | None
    knowledge_status: KnowledgeStatus
    section_counts: dict[str, int]


class BrandDnaOverview(BaseModel):
    active: BrandDnaVersionOut | None
    draft: BrandDnaVersionOut | None


class BrandDnaVersionList(BaseModel):
    versions: list[BrandDnaVersionSummary]


class DraftUpdateIn(BaseModel):
    document: BrandDnaDocument


class PublishIn(BaseModel):
    expected_draft_id: uuid.UUID


class GenerateIn(BaseModel):
    brief: BrandBriefIn
